[phases.setup]
nixPkgs = ["nodejs_20", "php83"]

[phases.install]
cmds = ["npm ci", "composer install"]

[phases.build]
cmds = ["npm run build"]

[phases.deploy]
cmds = ["php artisan optimize:clear", "php artisan migrate --force", "php artisan optimize"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"